dist: xenial
language: python
python: 3.7
cache: pip
env:
  - TOX_ENV=black
  - TOX_ENV=docslinks
  - TOX_ENV=flake8
  - TOX_ENV=mypy
  - TOX_ENV=py37
install: travis_retry python3.7 -m pip install tox
script: tox -e $TOX_ENV
