dist: bionic
language: python
python: 3.7
cache: pip

env:
  - TARGET=lint
  - TARGET=mypy
  - TARGET=pytest
  - TARGET=doclinks

before_install:
  - pip install poetry
install:
  - travis_retry poetry install -v
script:
  - poetry run make $TARGET
