sudo: false
language: python
cache: pip
python: 3.6
env:
  - TOX_ENV=black
  - TOX_ENV=docslinks
  - TOX_ENV=flake8
  - TOX_ENV=mypy
  - TOX_ENV=py36
install: travis_retry pip install tox
script: tox -e $TOX_ENV
