dist: xenial
language: python
cache: pip
env:
  - TOX_ENV=black
  - TOX_ENV=docslinks
  - TOX_ENV=flake8
  - TOX_ENV=mypy
  - TOX_ENV=py37
install: travis_retry pip install tox
script: tox -e $TOX_ENV
